apiVersion: v1
kind: Service
metadata:
  name: provider-svc
  labels:
    app: provider
spec:
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
    name: http
  selector:
    app: provider
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: provider-v1
spec:
  replicas: 1
  selector:
      matchLabels:
        app: provider  
  template:
    metadata:
      labels:
        app: provider
        version: v1
      annotations:
        linkerd.io/inject: enabled        
    spec:
      containers:
      - name: provider
        image: 938784100097.dkr.ecr.eu-west-2.amazonaws.com/provider-linkerd:1.0
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 100m
        ports:
        - containerPort: 5000